### ISSUE TITLE
New birthday quotes needed

### ISSUE THREAD

**Issue by gouravkhunger** [gouravkhunger/nextjs-birthday-wish#18]
Right now there are only [13 birthday quotes](https://github.com/gouravkhunger/nextjs-birthday-wish/blob/main/utils/birthdayWishes.js) to be shown on the wish.

You can add 10-15 new quotes so that there are more quotes to show.

**Comment by canaryGrapher** [comment]
I can do this!

**Comment by TishaJhabak1014** [comment]
@gouravkhunger plz let me work on this issue.

**Comment by gouravkhunger** [comment]
Hey @canaryGrapher and @TishaJhabak1014 
Both of you seem to have somewhat experience with git and github, I was wishing to give this task to some newbies. 

If in a day or two some new guy doesn't seek to work on this, I will refer back to you and know who wishes to work on it. 

Thanks for understanding, till then you can check out the codebase and find bugs/suggest feature requests/work on other issues :)

**Comment by notkanishk** [comment]
Hello @gouravkhunger, can I be assigned this?

**Comment by Mukta-Sawant** [comment]
@gouravkhunger  I would like to work on tis issue, please assign it to me.

**Comment by sounak999** [comment]
Hi, @gouravkhunger I really want to work on this issue. I have recently learned Git and GitHub and haven't contributed to open source yet. Via this Hacktober fest, I really want to contribute and learn new things. Hope you'll assign it to me. It'd be great learning.

**Comment by gouravkhunger** [comment]
Okay @notkanishk seems to be the best fit since he has the least number of contributions and it would be good to assign him this easier task for now.

For everyone: don't be sad that I didn't assign it to you, there are other issues pending on my projects, do check them out if you want to fix issues. Be free to suggest changes and new features too. Most of my projects are beginner friendly :)

**Comment by anish853** [comment]
Can I work on this issue@gouravkhunger

**Comment by anish853** [comment]
Can I work on this issue @gouravkhunger

**Comment by gouravkhunger** [comment]
@anish853 The issue has been resolved!
