### ISSUE TITLE
Go! button is not aligned

### ISSUE THREAD

**Issue by Mukta-Sawant** [gouravkhunger/nextjs-birthday-wish#19]
![Screenshot (4)](https://user-images.githubusercontent.com/77935961/135855400-7b68665f-704f-4986-a4c8-114cb9b8498c.png)

**Comment by gouravkhunger** [comment]
Oh damn I had tested on various devices, but maybe forgot to test on the lowest possible screen size xD. I fear if anyone uses such small devices these days lol.

Anyways, thanks for pointing out, do you wish to fix it? Just adding more margin right to the input below the `320px` break point would fix this ig.

**Comment by phoebeireland** [comment]
Hi, is anyone assigned to this? If not, can I be assigned please?

**Comment by gouravkhunger** [comment]
sure @phoebeireland go ahead, add the CSS in the home.module.css file just below the other media queries and you are good to go :)

**Comment by phoebeireland** [comment]
Did you want the button in the middle or to the far right?

**Comment by gouravkhunger** [comment]
@phoebeireland middle seems good
