### ISSUE TITLE
Add Documentation for Contribution Guidelines

### ISSUE THREAD

**Issue by shubhamjha25** [gouravkhunger/nextjs-birthday-wish#25]
While exploring the repository, I found that the proper instructions for contributing in the project is not mentioned.
I would like to create a new `Contributing.md` file where I will explain the steps of how to contribute.
It will help those who are new to open source and will enhance the productivity.

Also, a new section will be added in between **Local Setup** & **Learn More** named as **Contribution Guidelines** in the main `Readme.md` file. The link to the `Contributing.md` file will be provided there.

@gouravkhunger, If you find the idea useful, then do assign me to this issue so that I can start working on it as soon as possible.
Thanks! 😀

**Comment by gouravkhunger** [comment]
Sure, you can go ahead and add a basic `CONTRIBUTING.md` file(make sure the name is in caps).

Once you add them, I will tell you what more specifics are needed and we'll merge the PR.
