### ISSUE TITLE
Feature Request : Image Carousel

### ISSUE THREAD

**Issue by parthpanchal123** [gouravkhunger/nextjs-birthday-wish#3]
Allow the user to provide either a single image or a list of images, which then can be shown in a carousel rather than just a text greeting.

**Comment by gouravkhunger** [comment]
What kind of images?

**Comment by parthpanchal123** [comment]
The birthday girl/boys image or some memories the  greeter needs to share

**Comment by gouravkhunger** [comment]
I don't plan to have any database/api functionality for this project yet. Even if there is option to choose from a  static set of images, then the url scheme might need to be edited and that would make it kinda ugly. hbdwish.ml/<name> is fine for now. 

Thanks a lot, I will consider it in the future, if this project grows a lot as for now, I built this as a hobby project to learn next js.
