### ISSUE TITLE
Add birthday music 

### ISSUE THREAD

**Issue by Sejal-16** [gouravkhunger/nextjs-birthday-wish#32]
For now we can have one track playing along with birthday wish page.

**Comment by gouravkhunger** [comment]
Great idea! We can add some non copyright royalty free music. Please share it here and the source you would get it from, before working on the implementation 👍🏻

**Comment by Sejal-16** [comment]
Hey i ahve liked this : 
please let me know how you feel about this.

https://user-images.githubusercontent.com/65293021/136655251-f4b2da83-7a65-4564-b648-6548d19e743f.mp4

**Comment by gouravkhunger** [comment]
This one is good for now @Sejal-16 😄 
Make sure it isn't copyrighted and needs no attribution(if it does require attribution, add it to the credits section in README) :)

**Comment by haidarrifki** [comment]
hi, can i work on this issue @Sejal-16 @gouravkhunger ?
