### ISSUE TITLE
Default Nextjs favicon to be changed 

### ISSUE THREAD

**Issue by parthpanchal123** [gouravkhunger/nextjs-birthday-wish#4]
Currently int the browser tab we can see the default Nextjs favicon that can be potentially replaced with a nice logo or something like a bday cake etc .

**Comment by danger-ahead** [comment]
Consider assigning me.

**Comment by gouravkhunger** [comment]
@danger-ahead can you please attach the file that you will be putting as a favicon. Also, if you copy it from the internet, please do tell me where are you taking it from. Make sure to note if attributions are required or not.

Once you send the image and proof, I will assign it to you :)

**Comment by gouravkhunger** [comment]
Hey @danger-ahead since I didn't get any response from @parthpanchal123, will you consider following the above-mentioned steps so that I can assign the issue to you?

**Comment by parthpanchal123** [comment]
Sorry @gouravkhunger , what response were you expecting from me ?

**Comment by gouravkhunger** [comment]
Oh I am really sorry, I was expecting the response from @danger-ahead and by mistake, interchanged the pings. I am extremely sorry for that.

Can you please go through https://github.com/gouravkhunger/nextjs-birthday-wish/issues/4#issuecomment-932747527 comment and report back so that I can assign the issue to you?

**Comment by parthpanchal123** [comment]
I've gone through the comment, you can assign the issue to me!

**Comment by parthpanchal123** [comment]
How does this look ?
![image](https://user-images.githubusercontent.com/20091596/135744747-d7780e7b-3a74-4c2c-9379-13fc54f6727e.png)

This attribution is required in order to use it .
<div>Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>

**Comment by gouravkhunger** [comment]
Please do remove the background by using https://remove.bg website

**Comment by parthpanchal123** [comment]
Okay I'll do that ! Assign it to me and I'll send a PR

**Comment by parthpanchal123** [comment]
![image](https://user-images.githubusercontent.com/20091596/135746773-ffe739f4-a1ec-4430-89bc-7c9d99e3e87a.png)

Are there any style preferences for the footer? Currently, this one is the default they have suggested on their site .

**Comment by gouravkhunger** [comment]
It would be better if you just put the credit on the open source repo's readme as suggested. And I think you changed the font to ubuntu, please keep the default designs and change only the favicon and readme :)

**Comment by gouravkhunger** [comment]
It would be better in the readme, because this asset is not directly visible to users and is displayed in the browser tab only, and it is 24x24 px graphic, for that it is better to refer them in the README rather than the footer, as there is no icon visually represented in the website and it creates false interpretation.

**Comment by parthpanchal123** [comment]
Opened #16

**Comment by gouravkhunger** [comment]
Thanks, the PR has been merged :)

**Comment by gouravkhunger** [comment]
btw @parthpanchal123 , if you wish to suggest a good favicon for another Next.js app I made, you can open an issue in [its respective repo](https://github.com/gouravkhunger/nextjs-strikeit) :)
