### ISSUE TITLE
Change theme/color instead of default blue color 

### ISSUE THREAD

**Issue by adarshzpatel** [gouravkhunger/nextjs-birthday-wish#5]

**Comment by danger-ahead** [comment]
Consider assigning me. Also what would be the new color?

**Comment by gouravkhunger** [comment]
Do you want to change the blue colour? Or do you want to work on a feature where a person can choose what would be the theme color of the wish?

I don't plan to change the blue color itself, but it would be great if there is a custom option for dynamic color.

**Comment by adarshzpatel** [comment]
I meant blue will be default but the user has the option to choose from bunch of other color options such as green, orange, violet etc.

**Comment by adarshzpatel** [comment]
Let me know if you want me to work on it.

**Comment by gouravkhunger** [comment]
Sure, I would love to see that feature. Go ahead :)

**Comment by adarshzpatel** [comment]
Done!
