### ISSUE TITLE
Add a message along with birthday wish

### ISSUE THREAD

**Issue by Sejal-16** [gouravkhunger/nextjs-birthday-wish#7]
![image](https://user-images.githubusercontent.com/65293021/135715530-7874061f-a47c-41f3-b517-b01ab0672fcf.png)

Along with wishing the person we can add a randomly generated message to display with it like : 
Happy Birthday <User>!
May you have a successful and Wonderful year.

**Comment by gouravkhunger** [comment]
Thanks for the idea, if you are willing to work on this random message, I can assign it to you!

**Comment by Sejal-16** [comment]
Yes i will work assign me:)

**Comment by gouravkhunger** [comment]
The repo is eligible for hacktoberfest :)

**Comment by Sejal-16** [comment]
i was thinking i could make a file which contains an array of objects , these objects are random messages related to birthday like so:

`["hope all your birthday wishes and dreams come true." , "May the joy that you have spread in the past come back to you on this day", "May you be gifted with life’s biggest joys and never-ending bliss. After all, you yourself are a gift to earth, so you deserve the best."]` 

Then this file will be imported in [name].js .   Wherein i will create a random number between 0 and array.length . And then display the message. 

so where do you think in which folder i should keep the file of wishes.js ?

**Comment by gouravkhunger** [comment]
You can create a folder with name `util` and put it there, and import it inside the name file

**Comment by Sejal-16** [comment]
On it ! Thanks

**Comment by gouravkhunger** [comment]
Great!

**Comment by Sejal-16** [comment]
https://user-images.githubusercontent.com/65293021/135724158-ac3766e7-2aa5-470d-986b-b98a404aff06.mp4

It shows like this now. Can i go ahead and a pull request?

**Comment by gouravkhunger** [comment]
Awesome! Can you test is it responsive? If it's not, I believe you can copy some of the media queries from another next app of mine, [check out this file](https://github.com/gouravkhunger/nextjs-strikeit/blob/main/styles/Home.module.css) in the strikeit project.

Add the `desc` class to the text and it will become responsive as I have tested the other project and both have the same layout :)

**Comment by Sejal-16** [comment]
Yes i have added the desc class and tested it for responsive too.

**Comment by gouravkhunger** [comment]
Thank you! Make a PR, and I will test the preview build from vercel, and then we'll proceed to merge :)

**Comment by gouravkhunger** [comment]
Please refer to this issue, by adding `Fixes #7` somewhere in the title or in the description of the PR.

**Comment by Sejal-16** [comment]
Yes Sure , thanks !
